### ISSUE TITLE
WPF is ok, but UWP has this error

### ISSUE THREAD

**Issue by lizongying** [microsoft/Windows.UI.Composition-Win32-Samples#101]
<img width="609" alt="0" src="https://user-images.githubusercontent.com/16871545/152507677-f70834db-edec-4280-8089-47d1e094f626.png">

**Comment by robmikh** [comment]
The most common error from `CreateFromWindow` are because the window provided is not available to capture. Does this happen with all windows or just some windows? Is there an application that can reliably reproduce this error when captured?

**Comment by lizongying** [comment]
> The most common error from is because the window provided is not available to capture. Does this happen with all windows or just some windows? Is there an application that can reliably reproduce this error when captured?`CreateFromWindow`

same window

**Comment by lizongying** [comment]
> The most common error from `CreateFromWindow` is because the window provided is not available to capture. Does this happen with all windows or just some windows? Is there an application that can reliably reproduce this error when captured?

This error is raised for all windows

**Comment by lizongying** [comment]
GraphicsCapturePicker is no problem

**Comment by robmikh** [comment]
Ah sorry, I missed an important piece of information from your title. UWP and LowIL callers are blocked from calling `CreateFromWindow` and `CreateFromMonitor`, it's a Win32 only API.

To programmatically capture the screen, you'll need to use a different API:

1. Define the `graphicsCaptureProgrammatic` capability in your manifest.
2. Call `GraphicsCaptureAccess.RequestAsync` with `GraphicsCaptureAccessKind.Programmatic`.
3. Call [`GraphicsCaptureItem.TryCreateFromWindowId`](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscaptureitem.trycreatefromwindowid?view=winrt-22000#windows-graphics-capture-graphicscaptureitem-trycreatefromwindowid(windows-ui-windowid)).

You can obtain WindowIds from [`WindowServies.FindAllTopLevelWindowIds`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.windowmanagement.windowservices.findalltoplevelwindowids?view=winrt-22000#windows-ui-windowmanagement-windowservices-findalltoplevelwindowids). Keep in mind that these APIs were introduced in Windows 11, and will not work on previous versions of Windows.

**Comment by lizongying** [comment]
`GraphicsCapturePicker` doesn't seem to support XboxGameBarWidget, and can't find any `GraphicsCaptureItem`, which can be found on other pages. So I tried to use `CreateFromWindow`, and if it can be solved, thank you very much!

**Comment by robmikh** [comment]
Your best bet is using the new API on Windows 11.
