### ISSUE TITLE
Add sample for Mica Material

### ISSUE THREAD

**Issue by RaphMar2021** [microsoft/Windows.UI.Composition-Win32-Samples#104]
Super, this repository have Acrylic effect exemple but

can you add the Mica Material effect?

Thanks

**Comment by juan-** [comment]
Hi @RaphMar2021,
you can find the latest ways to apply Mica at 
https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/system-backdrop-controller

**Comment by raphm4044** [comment]
No thanks, i aldeary managed to make it work on Windows Forms (using P/Invoked DWM API methods)
