### ISSUE TITLE
Some samples use `WindowsRuntimeMarshal` class, that is no longer available in .NET 5+

### ISSUE THREAD

**Issue by lostmsu** [microsoft/Windows.UI.Composition-Win32-Samples#110]
Is there a replacement for .NET 5+?

[Example](https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/blob/a59e7586c0bd1a967e1e25f6ca0363e20151afe5/dotnet/WPF/ScreenCapture/Composition.WindowsRuntimeHelpers/CaptureHelper.cs#L79):
```csharp
public static GraphicsCaptureItem CreateItemForMonitor(IntPtr hmon)
{
    var factory = WindowsRuntimeMarshal.GetActivationFactory(typeof(GraphicsCaptureItem));
    var interop = (IGraphicsCaptureItemInterop)factory; 
    var itemPointer = interop.CreateForMonitor(hmon, GraphicsCaptureItemGuid);
    var item = Marshal.GetObjectForIUnknown(itemPointer) as GraphicsCaptureItem;
    Marshal.Release(itemPointer);

    return item;
}
```

**Comment by robmikh** [comment]
Take a look at this file:

https://github.com/robmikh/WPFCaptureSample/blob/master/Robmikh.WindowsRuntimeHelpers/CaptureHelper.cs

That repo has a version of WPF capture sample that's been updated for .NET 5/6.

**Comment by lostmsu** [comment]
@robmikh that did not immediately work due to my need to understand CSWinRT, so I ended up not using your code. But simply following [this table](https://github.com/microsoft/CsWinRT/blob/master/docs/interop.md#summary) I got a working sample, that does not need to use CSWinRT magic explicitly, and does not require `unsafe`:

```csharp
public static GraphicsCaptureItem CreateItemForMonitor(IntPtr hmon)
{
    var factory = GraphicsCaptureItem.As<IGraphicsCaptureItemInterop>();
    var itemPointer = factory.CreateForMonitor(hmon, GraphicsCaptureItemGuid);
    var item = GraphicsCaptureItem.FromAbi(itemPointer);
    Marshal.Release(itemPointer);

    return item;
}
```

**Comment by lostmsu** [comment]
@robmikh no plans to update the samples in this repo?

**Comment by robmikh** [comment]
It's on the list, currently getting the C++ samples updated.
