### ISSUE TITLE
Cannot use IGraphicsCaptureItemInterop::CreateForWindow with electron apps

### ISSUE THREAD

**Issue by YueLu0116** [microsoft/Windows.UI.Composition-Win32-Samples#111]
My Windows screen-capture sdk is built on winrt(c++) and work with electron through [c++ addons](https://nodejs.org/api/addons.html). However, every time I call `CreateForMonitor`, it will throw an access-deined exception. How can I solve this issue?  

Windows version: Windows 10 20H2 (19042.1706)
What I have tried:
1. run the electron application as Administrator
2. start the electron app with command line arguements: [--no-sandbox](https://www.electronjs.org/zh/docs/latest/api/command-line-switches#--no-sandbox)
3. I check the result of GetSidSubAuthority: `SECURITY_MANDATORY_HIGH_RID`

Some similar but unsolved issues:
1. https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/issues/49
2. https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/issues/55

**Comment by robmikh** [comment]
`IGraphicsCaptureItemInterop` is not available to LowIL callers, which would include the JavaScript process in Chromium. You'll need to either construct the item from at least a MediumIL process and marshal it to the LowIL process or use the newer [TryCreateFromWindowId](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscaptureitem.trycreatefromwindowid?view=winrt-22621) method added in Windows 11.

**Comment by YueLu0116** [comment]
> `IGraphicsCaptureItemInterop` is not available to LowIL callers, which would include the JavaScript process in Chromium. You'll need to either construct the item from at least a MediumIL process and marshal it to the LowIL process or use the newer [TryCreateFromWindowId](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscaptureitem.trycreatefromwindowid?view=winrt-22621) method added in Windows 11.

I call `GetSidSubAuthority` before calling `CreateForMonitor` and I always get `SECURITY_MANDATORY_HIGH_RID`. Does it mean the process is HighIL?

**Comment by robmikh** [comment]
How are you calling `GetSidSubAuthority`? What does it say when you query for `TokenIsAppContainer` from the process token? Unfortunately, I'm not very familiar with Electron, so I'm not sure how your steps are affecting the environment when we go to inspect the process token on the system side.

**Comment by YueLu0116** [comment]
Today I query `TokenIsAppContainer` following your advice. After this query, I call `CreateForMonitor` and everything works fine. Don't know what happened...

```cpp
void IsAppContainer() {
	HANDLE hToken = nullptr;
	if (OpenProcessToken(GetCurrentProcess(), TOKEN_QUERY, &hToken)) {
		DWORD dwSize = 0;
		BOOL fIsAppContainerProcess;
		if (!GetTokenInformation(hToken, TokenIsAppContainer, &fIsAppContainerProcess, sizeof(BOOL), &dwSize) ||
			dwSize != sizeof BOOL) {
			fIsAppContainerProcess = false;
		}
		if (fIsAppContainerProcess) {
			LOG("It is an app container. [fIsAppContainerProcess={}]", fIsAppContainerProcess);
		}
		else {
			LOG("It is NOT an app container. [fIsAppContainerProcess={}]", fIsAppContainerProcess);
		}
	}
	else {
		LOG("OpenProcessToken() error {}\n", (unsigned long)(GetLastError()));
	}
}
```

Codes for calling `GetSidSubAuthority`:
```cpp
DWORD GetProcessIL(TOKEN_INFORMATION_CLASS tokenInfoCls)
{
	DWORD dwRet = 0; {
		HANDLE hToken = NULL;
		if (OpenProcessToken(GetCurrentProcess(), TOKEN_QUERY, &hToken)) {
			DWORD dwSize = 0;
			// determine information length
			if (!GetTokenInformation(hToken, tokenInfoCls, NULL, 0, &dwSize) &&
				GetLastError() == ERROR_INSUFFICIENT_BUFFER) {
				PTOKEN_MANDATORY_LABEL TokenInfo = (PTOKEN_MANDATORY_LABEL)malloc(dwSize);
				if (TokenInfo) {
					// get an actual information
					if (GetTokenInformation(hToken, tokenInfoCls, TokenInfo, dwSize, &dwSize)) {
						// get the integrity level
						dwRet = *GetSidSubAuthority(
							TokenInfo->Label.Sid,
							(DWORD)(*GetSidSubAuthorityCount(TokenInfo->Label.Sid) - 1)
						);
					}
					else {
						LOG("GetSidSubAuthorityCount() error {}\n", (unsigned long)GetLastError());
					}
					free(TokenInfo);
				}
				else {
					LOG("Token allocation error {}\n", (unsigned long)(GetLastError()));
				}
			}
			else {
				LOG("GetTokenInformation() error {}\n", (unsigned long)(GetLastError()));
			}
			CloseHandle(hToken);
		}
		else {
			LOG("OpenProcessToken() error {}\n", (unsigned long)(GetLastError()));
		}
	}
	return dwRet;
}
```

**Comment by w0nche0l** [comment]
Hi @YueLu0116, so this worked after you called both of those functions? Is it that you stopped calling it as an admin?

**Comment by Lijian1122** [comment]
> Hi @YueLu0116, so this worked after you called both of those functions? Is it that you stopped calling it as an admin?

Do you resolve this problem when as admin
