### ISSUE TITLE
Can I do successive captures on two different windows

### ISSUE THREAD

**Issue by rjx-ray** [Microsoft/Windows.UI.Composition-Win32-Samples#116]
I can successfully capture a window without problems.
However I now need to capture 2 or more windows.
I am trying to do this by stopping the current capture with this code
`   if (m_capture) {
       m_capture->Close();
       m_capture = nullptr;
       m_itemClosedRevoker.revoke();
   }`
And then restarting with the new HWND
However on restart I get a winrt:hresult_error exception in interop_factory->CreateForWindow

Can this be made to work?

**Comment by robmikh** [comment]
Yea it should work. Can you share which build of Windows you're trying this on as well as the error code inside the `hresult_error` object?

**Comment by rjx-ray** [comment]
I'm running on Windows 11 Pro 22H2  SDK 10.0.19041.685

I'm having trouble getting the error code- this isn't working
<img width="943" alt="image" src="https://user-images.githubusercontent.com/24891831/212753992-f503652e-52b9-404e-b249-74c57e270c83.png">
CreateForWindow doesn't return, I just see
<img width="302" alt="image" src="https://user-images.githubusercontent.com/24891831/212754382-242e78e4-33cb-4ddf-8ef0-5d9de45aacfc.png">
Its complicated by the fact that I'm running the capture in a DLL as the main project can't use WinRT. The call stack is
<img width="452" alt="image" src="https://user-images.githubusercontent.com/24891831/212754691-6ca78f95-5e19-4a36-b616-6ee662cd8081.png">

**Comment by robmikh** [comment]
Usually this happens because the window you're trying to capture is deemed non-capturable by the shell. Is it always the same window? Does it work if you attempt to capture that window first? 

Does [this sample](https://github.com/robmikh/Win32CaptureSample) work for you for successive window captures?

**Comment by rjx-ray** [comment]
So if I try and capture the second window first I get the exception straight away. 
I'll investigate the differences between the windows tomorrow.

What could make a window non-capturable?

**Comment by robmikh** [comment]
The general rule of thumb is anything that shows up in the Alt+Tab view is considered capturable.

**Comment by rjx-ray** [comment]
Thanks for your help. I can now do the successive captures. 
But its pretty slow, averaging ~10fps and I'm having to wait up to 100ms for the new frame. I guess that's to be expected. 
Is it possible to run multiple simultaneous capture instances?

**Comment by robmikh** [comment]
I'm a little surprised you're seeing that kind of performance. What hardware are you running on?

Yes, you should be able to run more than one capture at once. There is a bug in Windows 10 when running multiple captures from the same GraphicsCaptureItem object though.

**Comment by rjx-ray** [comment]
Just to say that our main app can now use WinRT and I don't need to run the capture in a DLL any more. All these issues have now gone away and I can do multiple simultaneous captures at full speed
