### ISSUE TITLE
BSODs on 4 separate Hard Drives

### ISSUE THREAD

**Issue by Deadlydread** [Microsoft/Windows.UI.Composition-Win32-Samples#121]
Good Day. Can someone plz read my dump file for me, to see if they can help me figure why I have been getting constant BSOD on my PC. 4 different Hard Drives 2 of them New. 1 SSD All doing same thing. BSOD prevent me from even formatting the PC. It’s a Huananzhi x99 F8D with 64 Gb Ram. Xeon e5 2670 dual Cpu. 

Faulting application name: dwm.exe, version: 10.0.22000.1, time stamp: 0x7cbe2305
Faulting module name: ntdll.dll, version: 10.0.22000.1761, time stamp: 0x4308e1bc
Exception code: 0xc0000409
Fault offset: 0x00000000000935cf
Faulting process id: 0x2e54
Faulting application start time: 0x01d977e10c63f19e
Faulting application path: C:\Windows\system32\dwm.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 2fdceddc-4775-4dd8-8157-950679cd56d7
Faulting package full name:
Faulting package-relative application ID:

Faulting application name: vlc.exe, version: 3.0.16.0, time stamp: 0xa6d0a6c0
Faulting module name: ntdll.dll, version: 10.0.22000.1761, time stamp: 0x4308e1bc
Exception code: 0xc0000374
Fault offset: 0x000000000010c359
Faulting process id: 0x83c
Faulting application start time: 0x01d977c0b47d4e6d
Faulting application path: C:\Program Files\VideoLAN\VLC\vlc.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 0084446a-22ab-423d-836e-d63567f9e1ad
Faulting package full name:
Faulting package-relative application ID:

Faulting application name: dwm.exe, version: 10.0.22000.1, time stamp: 0x7cbe2305
Faulting module name: ntdll.dll, version: 10.0.22000.1761, time stamp: 0x4308e1bc
Exception code: 0xc0000409
Fault offset: 0x00000000000935cf
Faulting process id: 0xbb8
Faulting application start time: 0x01d977e11d11b91f
Faulting application path: C:\Windows\system32\dwm.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: fe937df3-3501-47d4-82ce-f18867350dcd
Faulting package full name:
Faulting package-relative application ID:

Audit events have been dropped by the transport. 0

Log Name: Application
Source: Application Error
Date: 4/25/2023 8:46:54 PM
Event ID: 1000
Task Category: (100)
Level: Error
Keywords: Classic
User: N/A
Computer: DESKTOP-F726TKR
Description:
Faulting application name: dwm.exe, version: 10.0.22000.1, time stamp: 0x7cbe2305
Faulting module name: D3D10Warp.dll, version: 10.0.22000.1641, time stamp: 0x31d94402
Exception code: 0xc0000005
Fault offset: 0x000000000031f04e
Faulting process id: 0x5c8
Faulting application start time: 0x01d977b7ca64963c
Faulting application path: C:\Windows\system32\dwm.exe
Faulting module path: C:\Windows\system32\D3D10Warp.dll
Report Id: ca590834-f632-4ed8-b740-998b35ebf12b
Faulting package full name:
Faulting package-relative application ID:
Event Xml:

1000
0
2
100
0
0x80000000000000

3763

Application
DESKTOP-F726TKR

dwm.exe
10.0.22000.1
7cbe2305
D3D10Warp.dll
10.0.22000.1641
31d94402
c0000005
000000000031f04e
5c8
01d977b7ca64963c
C:\Windows\system32\dwm.exe
C:\Windows\system32\D3D10Warp.dll
ca590834-f632-4ed8-b740-998b35ebf12b

**Comment by robmikh** [comment]
I recommend that you file feedback in the [Feedback Hub](https://apps.microsoft.com/store/detail/feedback-hub/9NBLGGH4R32N), which will get the report to the right team as well as let us investigate the blue screens you're seeing if you have diagnostic reporting turned on. Please mention any details you can when filing feedback, most critically if it happens during any specific task. You've listed vlc, does it happen when playing video or is that just one incident? Information you provide in the feedback hub that can help us narrow things down will assist in any investigation into your issue.

**Comment by Deadlydread** [comment]
Thanks I did as suggest about Feedback Hub. However I am getting BSODs more often now. Do U think it's a possibility that it's my 550w PSU. I don't want to spend $ on the 850w I am looking at and still have same issues. I know now it's NOT the Hard Drives. I do remember customer concerns when I was buying the 3060 RTX was the PSU wattage. I am also running dual CPU with a Molex adapter from SATA bcuz the PSU only have 1 CPU connector. Could any of these be the issue?

**Comment by robmikh** [comment]
Sorry, but this isn't a general technical support forum. We will go through the information you've provided to us, but you may want to seek out a specialist about your hardware questions.

I'm closing this issue for now, as this is all we can do through this medium.
