### ISSUE TITLE
[Request] Option to disable the yellow border around the window or change it's color (GraphicsCaptureSession)

### ISSUE THREAD

**Issue by gileli121** [microsoft/Windows.UI.Composition-Win32-Samples#40]
Hello, thank you very much for the new API to capture windows (cpp\ScreenCaptureforHWND) .

I will be very grateful to you if you add option to disable the yellow border (in addition to the option I will make to disable mouse capture). Or at least change the color of the border to different color

I am talking about:
![image](https://user-images.githubusercontent.com/17680514/62074260-06ed0a00-b24b-11e9-98f7-c718200b4ad3.png)
 
Thanks.

**Comment by Tar4s** [comment]
I'm afraid this is part of API 🤔

**Comment by gileli121** [comment]
You mean that I can do it?
How? I did not found any documentation about it.

**Comment by krenner** [comment]
Hi - The application can not modify the border at this time.  Capture documentation is [here](https://blogs.windows.com/windowsdeveloper/2019/09/16/new-ways-to-do-screen-capture/)
