### ISSUE TITLE
Path geometries in WPF

### ISSUE THREAD

**Issue by mgnslndh** [microsoft/Windows.UI.Composition-Win32-Samples#45]
Is it possible to create a CompositionPath from WPF? It seems I need to pass a `Windows.Graphics.IGeometrySource2D` to the contructor of `CompositionPath` but I do not know how to get a `Windows.Graphics.IGeometrySource2D` implementation from WPF.  Preferably something like [CanvasPathBuilder](https://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_Geometry_CanvasPathBuilder.htm).

**Comment by robmikh** [comment]
This isn't possible with WPF paths. You could maybe convert them to D2D paths manually and implement `Windows.Graphics.IGeometrySource2D` and `Windows.Graphics.IGeometrySource2DInterop`, but it would generally be easier to use Win2D.
