### ISSUE TITLE
winrt::hresult_access_denied in CreateForWindow in some cases

### ISSUE THREAD

**Issue by shuangshu** [microsoft/Windows.UI.Composition-Win32-Samples#49]
Hello,
I am using nodejs load dll A and then dll A load dll B which internal calls IGraphicsCaptureItemInterop.CreateForWindow but I encounter winrt::hresult_access_denied
when I using MFC just to load dll B internal calls IGraphicsCaptureItemInterop.CreateForWindow work fine.
is it a program permission problem?

**Comment by robmikh** [comment]
Could you tell us what build of Windows you're trying this on?

We block calls to CreateForWindow and CreateFromMonitor in two cases:

- The caller is not at least Medium IL (integrity level)
- The caller is a UWP (AppContainer)

My guess is that the javascript engine is being run in a LowIL process and is being blocked.

**Comment by shuangshu** [comment]
hi  robmikh,
 windows 10(1903) and the electron app run as administrator

**Comment by jpark37** [comment]
We saw this with CEF on OBS. The issue there was that the Chromium sandbox was not properly disabled, and this function was eventually being called:
https://cs.chromium.org/chromium/src/sandbox/win/src/restricted_token_utils.cc?l=341

This was only a problem when running as administrator for whatever reason. We have since submitted a patch to CEF, and moved past this issue. Good luck.

**Comment by w0nche0l** [comment]
Sorry to necro this thread, but I'm also seeing this whenever my app is being ran as administrator. 

@jpark37 when you say "We have since submitted a patch to CEF, and moved past this issue." Do you mean that the patch solved your issue, or that you decided to let it be a known issue?

**Comment by jpark37** [comment]
The patch allows us to solve our issue.

We set CefSettings::no_sandbox to false:
https://github.com/obsproject/obs-browser/blob/a4e163ec8a156f090f3a0db7e6f992a4adad3bb6/obs-browser-plugin.cpp#L313

And we pass nullptr for windows_sandbox_info to CefInitialize, which now behaves the way we want:
https://github.com/obsproject/obs-browser/blob/a4e163ec8a156f090f3a0db7e6f992a4adad3bb6/obs-browser-plugin.cpp#L390
