### ISSUE TITLE
GraphicsCaptureItem.CreateFromVisual() with a WPF element?

### ISSUE THREAD

**Issue by joedemax** [microsoft/Windows.UI.Composition-Win32-Samples#54]
Hi. T

Trying to use the new Graphics Capture API to capture a WPF window. Can anyone give me some pointers as to how I would use CreateFromVisual using a WPF window rather than UWP?

Joe

**Comment by robmikh** [comment]
Unfortunately that isn't possible at this time. WPF does not use WinRT Visuals to compose its UI, to the compositor it just looks like a single swap chain. The best that can be done currently is to capture the window using its HWND to create a GraphicsCaptureItem.

**Comment by robmikh** [comment]
For example, if you know the window of your application that you want to capture you can do something like this:

```csharp
var myWPFWindow = /* Your WPF window */;
var interop = new WindowInteropHelper(myWPFWindow);
var windowHandle = interop.Handle;

var captureItem = CaptureHelper.CreateItemForWindow(windowHandle);
```

You can find the `CaptureHelper` static class [here](https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/blob/master/dotnet/WPF/ScreenCapture/Composition.WindowsRuntimeHelpers/CaptureHelper.cs).

**Comment by joedemax** [comment]
Many thanks for this. Unfourtunately I don't think think this will work for what I'm trying to do. I'm rendering some graphics in a WPF window which I need to be hidden from the user. Unfourtunately as soon as I set Window Visibility to hidden, the capture stops working.

**Comment by Zofware** [comment]
@joedemax graphics capture in UWP is the same: capture doesn't work on items that are hidden (or "Collapsed" in UWP/Xaml). The workaround, in UWP/Xaml at least, is to move the item off-screen without collapsing it.

**Comment by joedemax** [comment]
@Zofware  have you had any success with this? I found as soon as a some of the window was offscreen, that portion would no longer be capture.

**Comment by robmikh** [comment]
Applications may choose not to redraw portions of themselves that are off-screen. It really depends on how these applications compose themselves. For example, if an application uses DirectComposition or Windows.UI.Composition, that application should redraw just fine when it is off-screen. Many D3D/swap chain based applications will draw fine when they are off-screen. However applications that rely on their GDI redirection surface may not (depending on how they react to WM_PAINT messages).

How are you rendering your graphics to your window? Are you mixing it with other WPF content or just using it as a host?

**Comment by Zofware** [comment]
@joedemax FWIW I use the offscreen technique with a UWP Xaml app. I haven't tried it with anything else. I'll defer to @robmikh for how it should work with HWND capture.

**Comment by JordanSjodinFaithlife** [comment]
@robmikh would I be able to use the same tactic to capture a WPF window that is offscreen?

**Comment by robmikh** [comment]
I don’t believe a WPF window will repaint while offscreen.
