### ISSUE TITLE
How to add an image to HelloComposition

### ISSUE THREAD

**Issue by AndyPullis** [microsoft/Windows.UI.Composition-Win32-Samples#57]
The dotnet WPF HelloComposition example is great starting point for an application I need to develop, but I would like to know how to display an image behind the rectangles. For example, I have an image of people and I want to draw a box around each persons face. The image will be updated at 60 fps coming from a camera. The image comes in as a IntPtr to a byte array, of which i know the image width, height, and stride so it can be converted to a Bitmap. I have successfully taking in the images and displayed them on a WindowsFormHost control with a picturebox. But that is not ideal and I don't  know how to draw boxes and such on that in realtime. The visual layer seems like it would have the performance I desire since it uses the GPU. I would like to display the images, and draw sprite boxes at the location of each persons face. I have an algorithm to calculate the x,y coordinates and sizes of the boxes. If the IntPtr thing is too complicated, for now i would be happy with how to load a .bmp file from disk, at runtime, and display it on the CompositionHostElement, and then add random sprite boxes on top as the demo currently does.

Any help with this would be greatly appreciated.

**Comment by robmikh** [comment]
There are two approaches you could take:

1.  Load your image into a surface and use that with the Composition APIs.
2.  Continue to load your image using WPF or WinForms, and put the rectangle on top of it using the Composition APIs.

## Loading an image into a surface
When it comes to (1), this is unfortunately not something that you get for free in C#. You have two options here as well: you can either use COM interop (some manual and some through SharpDX) or you can use Win2D/other WinRT components. If you'd like to take a look at Win2D, here are some resources:

- [Using Win2D in a WPF application](https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/tree/master/dotnet/WPF/AcrylicEffect/AcrylicEffect)
- [Using WinRT components in desktop applications](https://blogs.windows.com/windowsdeveloper/2019/04/30/enhancing-non-packaged-desktop-apps-using-windows-runtime-components/)
- Some APIs you'll need to get going with this in Win2D:
   -  [CanvasComposition.CreateCompositionGraphicsDevice](https://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_UI_Composition_CanvasComposition_CreateCompositionGraphicsDevice.htm)
   - [CanvasBitmap.CreateFromBytes](https://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_CanvasBitmap_CreateFromBytes.htm)
   - [CanvasComposition.CreateDrawingSession](https://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_UI_Composition_CanvasComposition_CreateDrawingSession.htm)

If you'd like to go the SharpDX route, I would look at some of our C++ samples that load images into surfaces to get a feel for what APIs you'll need to call and find their equivalents in SharpDX/C#. I would also check out the [Direct3D11Helper](https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/blob/master/dotnet/WPF/ScreenCapture/Composition.WindowsRuntimeHelpers/Direct3D11Helper.cs) and [CompositionHelper](https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/blob/master/dotnet/WPF/ScreenCapture/Composition.WindowsRuntimeHelpers/CompositionHelper.cs) utilities in the [WPF Screen Capture sample](https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/tree/master/dotnet/WPF/ScreenCapture). Those helpers won't have everything you need but will help get you started.

Regardless if you use SharpDX or Win2D, here's the high level steps you'll need to take:

1. Create a D3D Device (D3D11Device/CanvasDevice)
2. Create a `CompositionGraphicsDevice` from your D3D device and `Compositor`
3. Create a `CompositionDrawingSurface` using the `CompositionGraphicsDevice`
4. Hook up the surface into the visual tree (e.g. place your surface into a `CompositionSurfaceBrush` and assign the brush to a `SpriteVisual` that is part of your visual tree. Don't forget to set a size on the visual!).
5. Update the surface:
    a. Create texture that contains your bits
    b. Draw/Copy that texture into the surface

## Placing squares over the image
This part is the easiest. For each square you'd like to place, create a `SpriteVisual`, and a `CompositionNineGridBrush`. Set the insets for the nine grid brush, and give its `Source` property some kind of `CompositionColorBrush` or a different kind of brush. 

If you know the size and center of the face, you can do something like this:
```csharp
var visual = compositor.CreateSpriteVisual();
// Maybe consider inflating the size of the visual to 
// compensate for the thickness of the border?
visual.Size = new Vector2(faceWidth, faceHeight);
visual.AnchorPoint = new Vector2(0.5f, 0.5f);
var brush = compositor.CreateNineGridBrush();
brush.SetInsets(5, 5, 5, 5);
brush.Source = compositor.CreateColorBrush(Colors.Red);
visual.Brush = brush;

// This assumes that x and y are relative to the top left of the image and that the 
// visual's origin is also at the top left of the image. You may need to add an 
// additional offset based on where the image is in your visual tree. 
visual.Offset = new Vector3(x, y, 0);
```

**Comment by teh173** [comment]
@robmikh  Is it possible to use LoadedImageSurface from a C++/WPF application?
https://docs.microsoft.com/en-us/windows/uwp/composition/composition-brushes#paint-with-an-image
It works fine under a UWP app but under Win32 I get the error:
The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))'
Which makes me think it needs a CoreDispatcher or I'm missing some initialization step.  Just some general feedback for Microsoft docs, it is sometimes very difficult to understand what is and is not allowed from Win32...

**Comment by robmikh** [comment]
I don't think it is possible, mainly because it is part of the XAML framework. If XAML isn't initialized, then I don't think LoadedImageSurface would work.

You'll need to do what I described above to manually use D3D/D2D to draw your images into composition surfaces.

Thanks for the feedback on the documentation, that's definitely something we've been trying to clean up.
