### ISSUE TITLE
AcrylicEffect - Could not find Windows Runtime type

### ISSUE THREAD

**Issue by AndyPullis** [microsoft/Windows.UI.Composition-Win32-Samples#58]
Hi,
I am getting this runtime error when I try to run the dotnet WPF AcrylicEffect solution. I've selected Debug x64 build and I haven't altered any code.

I am using Visual Studio 2019 v 16.5.5
Windows 10 LTSC Version 1809 Build 17763

![image](https://user-images.githubusercontent.com/26907376/82471558-73f8b700-9a8c-11ea-8a46-1f9054980728.png)

**Comment by AndyPullis** [comment]
What about this project requires Win 10 version 1903?

Thanks

**Comment by robmikh** [comment]
1903 is required for reg-free activation, which is needed to use non-system WinRT components from a non-packaged application. This is certainly why activating the `CanvasDevice` object is failing for you. You can read more about reg-free activation here: https://blogs.windows.com/windowsdeveloper/2019/04/30/enhancing-non-packaged-desktop-apps-using-windows-runtime-components/

**Comment by robmikh** [comment]
Closing this issue for now. If you have issues on a post-1903 build, please let us know.
