### ISSUE TITLE
Possible to build GraphicsCaptureItem from HWND, for win10 1809?

### ISSUE THREAD

**Issue by chen2qu** [microsoft/Windows.UI.Composition-Win32-Samples#62]
I have a question on how to build a GraphicsCaptureItem from current window's HWND in Win10 1809. We want to use Windows.Graphics.Capture APIs to capture our own win32 C++ application to a video. The problem is that we're all on Win10 1809, and CreateForWindow is added in Win10 1903. So it's a problem for us to get the GraphicsCaptureItem item for our window the capture. Any idea on how I can do this? Appreciated for any help or comment!

**Comment by robmikh** [comment]
As you noted, we added the CreateForWindow API in the 1903 build. Unfortunately it is unavailable to prior versions of Windows. On the 1809 build you'll need to use the picker to initiate a screen capture.

**Comment by chen2qu** [comment]
I see. Our case is that we just want to record our won app so it's kind of weird and unnecessary to launch the picker. Anyway thanks for the reply.
