### ISSUE TITLE
How to capture the screen and excluding a WPF window with WDA_EXCLUDEFROMCAPTURE?

### ISSUE THREAD

**Issue by HarrisonKawagoe3960X** [microsoft/Windows.UI.Composition-Win32-Samples#64]
I am developing a WPF app by using Windows.Graphics.Capture, like ScreenCapture in this repository.
I was succeed to exclude the specific window in my app by using SetWindowDisplayAffinity and WDA_MONITOR but it returns black area in my video.  I heard that WDA_EXCLUDEFROMCAPTURE can make the area transparent in C++, how to define or use WDA_EXCLUDEFROMCAPTURE in C#?

**Comment by robmikh** [comment]
This is only available to newer versions of Windows. Starting with 10.0.19041.0, a new value is available that you can pass to SetWindowDisplayAffinity. That value is `WDA_EXCLUDEFROMCAPTURE` (found alongside `WDA_MONITOR` in winuser.h).

`WDA_MONITOR` will black-out the window it is applied to.
`WDA_EXCLUDEFROMCAPTURE` will make the window transparent.

**Comment by HarrisonKawagoe3960X** [comment]
I'm succeed to use `WDA_EXCLUDEFROMCAPTURE` to exclude the specific Window and make it transparent in the latest version of Windows. Thanks!
Please allow me to ask a new question. Is it possible to excluding specific Window and making it transparent when capturing the screen in elder version of Windows 10? Not every user updated to latest version of Windows so I'm finding a way to make my app which uses Windows.Graphics.Capture implements this function in elder version of Windows 10

**Comment by robmikh** [comment]
Unfortunately, no. This functionality required a change in the operating system to expose.

**Comment by BenRussert** [comment]
> This is only available to newer versions of Windows. Starting with 10.0.19041.0, a new value is available that you can pass to SetWindowDisplayAffinity. That value is `WDA_EXCLUDEFROMCAPTURE` (found alongside `WDA_MONITOR` in winuser.h).
> 
> `WDA_MONITOR` will black-out the window it is applied to.
> `WDA_EXCLUDEFROMCAPTURE` will make the window transparent.

@robmikh, I've had a hard time finding updated docs on this or mention [other than this blog post](https://blogs.windows.com/windowsdeveloper/2019/09/16/new-ways-to-do-screen-capture/). Are there docs someplace I've missed?

Currently the electron project uses `WDA_MONITOR` which produces an empty black rectangle where the window would be. I opened [this PR](https://github.com/electron/electron/pull/24274) in hopes of properly feature detecting and using `WDA_EXCLUDEFROMCAPTURE` when supported. It would be awesome if you had a chance to look!

**Comment by robmikh** [comment]
Yes, we need to get that documented. Thanks for bringing that up!

As far is the PR, I have a general note. I gave this approach a try, and it wasn't what I was expecting. It appears setting `WDA_EXCLUDEFROMCAPTURE` on Windows 10 version 1903 succeeds but behaves as if WDA_MONITOR is applied. And it looks like this has always been the behavior. Although I'd like to test that before I say that definitively...

**Comment by BenRussert** [comment]
> behaves as if WDA_MONITOR is applied

The behavior the PR is going for is to make the window transparent (if the Windows version supports it), and fall back to black/`WDA_MONITOR` if not. The analogous code for Mac systems when electron's `setContentProtection` is called makes the window transparent, so this would make things more similar for windows systems that can support `WDA_EXCLUDEFROMCAPTURE`.

**Comment by robmikh** [comment]
I've updated the documentation to `SetWindowDisplayAffinity` to hopefully make this a bit clearer (but honestly it probably needs an overhaul).

What I was trying to point out is that `SetWindowDisplayAffinity` *won't fail* on older versions of Windows when you pass in `WDA_EXCLUDEFROMCAPTURE`. Instead it will behave as if `WDA_MONITOR` is set. So the check you're doing in the PR isn't necessary. You can always pass the new value and on newer systems it will be transparent and on older systems it will be replaced with a black box.
