### ISSUE TITLE
Could I user ScreenCaptureforHWND to capture the whole screen?When I change the hwnd to desktop,my program throws an exception in CreateCaptureItemForWindow.

### ISSUE THREAD

**Issue by cqhblg** [microsoft/Windows.UI.Composition-Win32-Samples#68]
![image](https://user-images.githubusercontent.com/29913470/91285520-e67ddf00-e7bf-11ea-85b8-4612a089a3de.png)
![image](https://user-images.githubusercontent.com/29913470/91285648-11683300-e7c0-11ea-89b1-3b35ef819b3d.png)

**Comment by robmikh** [comment]
You can capture a given monitor using [`CreateForMonitor`](https://docs.microsoft.com/en-us/windows/win32/api/windows.graphics.capture.interop/nf-windows-graphics-capture-interop-igraphicscaptureiteminterop-createformonitor).

**Comment by robmikh** [comment]
Here's an expanded version of that header:

https://github.com/robmikh/Win32CaptureSample/blob/master/Win32CaptureSample/util/capture.desktop.interop.h

**Comment by cqhblg** [comment]
Thank you!!!
