### ISSUE TITLE
How to capture window-content only?

### ISSUE THREAD

**Issue by Frixs** [microsoft/Windows.UI.Composition-Win32-Samples#74]
Hello,

how is it possible to capture only user content of selected window in [ScreenCapture](https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/tree/master/dotnet/WPF/ScreenCapture) project?

I want to achieve to capture window without Window's control bar on the top and capture just the user content area.
Similar approach is presented [here](https://www.codeproject.com/Articles/19192/How-to-capture-a-Window-as-an-Image-and-save-it) using `GetDC()` instead of `GetWindowDC()` from **User32**

Thank you for your assistance!

**Comment by robmikh** [comment]
Unfortunately, capturing only the client area is not available at this time. You'll need to calculate the window's client area rect and copy that out of the buffer we provide.

You'll likely need to use a mix of [ClientToScreen](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-clienttoscreen), [DwmGetWindowAttribute](https://docs.microsoft.com/en-us/windows/desktop/api/dwmapi/nf-dwmapi-dwmgetwindowattribute), and [DWMWA_EXTENDED_FRAME_BOUNDS](https://docs.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute).

**Comment by BenShapira** [comment]
Hey Rob,
Wanted to check in if this is something that might have been added since your last comment?

**Comment by robmikh** [comment]
Unfortunately not.
