### ISSUE TITLE
Unable to place any controls on top of WPF Acrylic blur

### ISSUE THREAD

**Issue by SelastinGeorge** [microsoft/Windows.UI.Composition-Win32-Samples#80]
I was trying to place one button over the acrylic control but the button appears to be under the control like this:

![image](https://user-images.githubusercontent.com/72641365/105273800-fe685c00-5bc1-11eb-9d42-8dd3f54e0c25.png)

I have tried changing  `_compositorDesktopInterop.CreateDesktopWindowTarget(HwndHost, true, out _compositionTarget);`

second argument to false (topmost), but it doesn't work. is this because Direct composition can draw only on top of all other controls.

**Comment by robmikh** [comment]
The issue is that WPF composes all of its content into one surface. From the perspective of the system compositor, there is only one bitmap that we see. As such, we can only compose dcomp/WUC content above or bellow that bitmap. This is sometimes referred to as the "airspace problem". 

If you could separate the content that is supposed to be "above" and "bellow" the visual, you could make this work. Unfortunately, I don't know off the top of my head how to achieve this in WPF.

**Comment by SelastinGeorge** [comment]
I have almost spend two weeks on this issue but no luck, i was able to fix
the flickering issue of the acrylic content on resize, but this is beyond
my knowledge.

Will it be possible to get the final bitmap or the backdrop brush as bitmap
, then it is possible to solve this issue. Is there any way that we could
make use of D3D10Image class to get the bitmap.

**Comment by SelastinGeorge** [comment]
So there is no way to do this. In .NET 4.5 they have introduced two properties to fix this aerospace problem, but it has been removed on the next releases.

> 1.3.10 Windows Presentation Foundation (WPF)
> 
> 1.3.10.1 HwndHost feature has been removed from WPF in the .NET Framework 4.5 Beta
> 
> The .NET Framework 4.5 Developer Preview included a WPF HwndHost redirection feature. However, this feature had several known issues and has been removed from the .NET Framework 4.5 Beta. It will not be included in any future releases.
> 
> To resolve this issue:
> 
> No workaround is available.

**Comment by robmikh** [comment]
Unfortunately it looks like the only way to get this to work is to fake it. If you knew what content was to be underneath, you could manually apply the effects yourself using Win2D or D2D. However, that solution is imperfect and imposes constraints on what can be placed underneath the effect area without breaking the illusion.

**Comment by SelastinGeorge** [comment]
But there is no way to get the host backdrop brush without a Compositor. I
have tried all the way I could and also tried some alternatives like using
desktop background as backdrop but when it comes to aero snap that one
breaks.

Here is the demo (when using desktop background) :
https://youtu.be/V-G8s-ol6p4

Here is the demo using this acrylic blur : https://youtu.be/_SV-s4Q4O1s

Both have a very good diffrence. But when rendering to wpf window both of
them will overlays the contents because they both use direct composition.

The desktop background acrylic uses IDComposition.
