### ISSUE TITLE
Security vulnerability that allows bypassing and removing the screen capture yellow border

### ISSUE THREAD

**Issue by gileli121** [microsoft/Windows.UI.Composition-Win32-Samples#91]
Hello,
I found a security bug that allows bypassing and removing the screen capture yellow border without any user permission.
So the window gets captured without any border!

Is there a way to get paid for it?
I want to report and in return get paid...
Where I can start?

Thanks.

**Comment by robmikh** [comment]
https://www.microsoft.com/en-us/msrc/bounty

**Comment by gileli121** [comment]
@robmikh 
Reported:
https://msrc.microsoft.com/report-detail/VULN-054714
