### ISSUE TITLE
Bug in `IsWindowValidForCapture` method/logic.. How to get it right?

### ISSUE THREAD

**Issue by gileli121** [microsoft/Windows.UI.Composition-Win32-Samples#99]
Hello, 
I noticed that in the example you have a helper method called `IsWindowValidForCapture()`. I found it useful
But unfortunately, I found a case when it does not work right. Your example ignores any `explorer.exe` windows.

If run the example, I can't see `explorer.exe` windows.
However, If I modify it and add the following lines in `Window_Loaded` while `0x0000000000020A1E` is the handle to explorer window:
```c#
var targetHwnd = new IntPtr(0x0000000000020A1E);
StartHwndCapture(targetHwnd);
```
Then it will be able to capture it:
![image](https://user-images.githubusercontent.com/17680514/150617891-7a5df04a-c6a8-45b3-9cfc-95e8ab8d277c.png)

It just doesn't suggest selecting this window for some reason.

This is how your example check whatever the window is valid for capture:
`WindowEnumerationHelper.IsWindowValidForCapture(p.MainWindowHandle)`
While `p` is the window process.

I found out that this line will return false.
To isolate it and reproduce it directly, run this code:
```c#
var p = Process.GetProcessesByName("explorer").First();
var valid = WindowEnumerationHelper.IsWindowValidForCapture(p.MainWindowHandle);
```

As you will see, it will return `false`
![image](https://user-images.githubusercontent.com/17680514/150618061-706c0ab6-35bf-4ce1-9382-c9a026e44a1f.png)

After more investigation, I found out that it is because the code using `MainWindowHandle` of the process instead of the actual window handle (eg: `0x0000000000020A1E` in my case)

Changing the handle to the direct window handle will solve the problem. However, unfortunately, this will create another problem that for some other windows the method will return `true` while capturing will always fail.

An example of such a window is the following `Git Extensions` window
![image](https://user-images.githubusercontent.com/17680514/150618214-25439953-d8bf-4ca9-b761-1cc121e6c40d.png)

Using `MainWindowHandle` here will return the correct result (`false` and indeed the capture will fail) but once I will use here the direct window handle, it will return `true`. And again, if I use the direct handle it will work wrong with `explorer` windows.

So it looks like something is not working fine with the logic here.
I don't know what is the correct way to do it.

Anyway, it looks like the native picker provided by the API is working fine:
![image](https://user-images.githubusercontent.com/17680514/150618387-56f56d17-fa66-4848-aa1a-354ed0d0e958.png)

It doesn't show to pick the "Git Extensions" window that I showed earlier while it still shows the explorer window.
So this native picker got it right in both cases. 

So there must be a way to do it without the picker.

**Comment by gileli121** [comment]
I think that this code is correct. But you will need to adjust the caller to not use `MainWindowHandle` from `p` and instead use the direct window handle.. Let me know if my fix is right. Changes descriptions in the comments:

```c#
public static bool IsWindowValidForCapture(IntPtr hwnd)
{
	if (hwnd.ToInt32() == 0)
	{
		return false;
	}

	if (hwnd == GetShellWindow())
	{
		return false;
	}


	// Removed:
	// if (!IsWindowVisible(hwnd))
	// {
	//     return false;
	// }

	// And replaced with:
	if (!IsWindowVisible(hwnd))
	{
		bool cloaked;
		var hrTemp = DwmGetWindowAttribute(hwnd, DWMWINDOWATTRIBUTE.Cloaked, out cloaked, Marshal.SizeOf<bool>());
		if (hrTemp == 0 && cloaked)
		{
			return false; // Window is not visible and also not background UWP invisible window
		}
	}

	// Removed:
	// if (GetAncestor(hwnd, GetAncestorFlags.GetRoot) != hwnd)
	// {
	//     return false;
	// }

	// And replaced with:
	if (GetAncestor(hwnd, GetAncestorFlags.GetParent) != IntPtr.Zero)
	{
		return false;
	}


	var style = (WindowStyles)(uint)GetWindowLongPtr(hwnd, (int)GWL.GWL_STYLE).ToInt32();
	if (style.HasFlag(WindowStyles.WS_DISABLED))
	{
		return false;
	}



	return true;
}
```

**Comment by robmikh** [comment]
The sample is just one example implementation. Each application will have different needs and you can tailor yours to your specific requirements. The ScreenCaptureforHWND sample might have a different behavior that you're looking for, it doesn't depend on the MainWindowHandle property.
